{"uuid": "ff7d1b39-c026-4b44-a49b-3771774b17a1", "children": ["6e01f81f-0424-4a3a-9e0a-46e24f3771b6"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1709287353911, "stop": 1709287353911}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=122.0.6261.70)\nStacktrace:\n\tGetHandleVerifier [0x00EE8C93+51395]\n\t(No symbol) [0x00E55EF1]\n\t(No symbol) [0x00D0E13A]\n\t(No symbol) [0x00CF25F2]\n\t(No symbol) [0x00D69B2B]\n\t(No symbol) [0x00D79E66]\n\t(No symbol) [0x00D63C26]\n\t(No symbol) [0x00D3C629]\n\t(No symbol) [0x00D3D40D]\n\tGetHandleVerifier [0x01266453+3711107]\n\tGetHandleVerifier [0x012A583A+3970154]\n\tGetHandleVerifier [0x012A0B28+3950424]\n\tGetHandleVerifier [0x00F99C99+776393]\n\t(No symbol) [0x00E616C4]\n\t(No symbol) [0x00E5C5A8]\n\t(No symbol) [0x00E5C759]\n\t(No symbol) [0x00E4DD80]\n\tBaseThreadInitThunk [0x76277BA9+25]\n\tRtlInitializeExceptionChain [0x77CEBD2B+107]\n\tRtlClearBits [0x77CEBCAF+191]\n\n", "trace": "  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"c:\\Users\\lenovo\\Desktop\\AutomationTesting\\Tests\\TestClasses\\conftest.py\", line 29, in log_on_failure\n    allure.attach(driver.get_screenshot_as_png(), name=\"Screenshot\", attachment_type=AttachmentType.PNG)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 836, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 847, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1709287404421, "stop": 1709287404428}], "start": 1709287353911, "stop": 1709287404428}